// auth
export const FETCH_USER = 'FETCH_USER'

// song
export const FETCH_SONGS = 'FETCH_SONGS'
export const PLAY = 'PLAY'
export const PAUSE = 'PAUSE'
export const REPLAY = 'REPLAY'
export const SELECT_SONG = 'SELECT_SONG'
export const CLEAR_SELECTED_SONG = 'CLEAR_SELECTED_SONG'
export const CHANGE_FONT_SIZE = 'CHANGE_FONT_SIZE'
export const CHANGE_SCROLL_SPEED = 'CHANGE_SCROLL_SPEED'
export const TRANSPOSE_SONG = 'TRANSPOSE_SONG'
export const RESET_TRANSPOSE = 'RESET_TRANSPOSE'
export const TOGGLE_CONTROLS = 'TOGGLE_CONTROLS'
export const SCROLL_COMPLETE = 'SCROLL_COMPLETE'
export const EDIT_COMPLETE = 'EDIT_COMPLETE'

// playlist
export const FETCH_PLAYLISTS = 'FETCH_PLAYLISTS'
export const SELECT_PLAYLIST = 'SELECT_PLAYLIST'
export const SET_PLAYLIST_SONGS = 'SET_PLAYLIST_SONGS'
export const CLEAR_SELECTED_PLAYLIST = 'CLEAR_SELECTED_PLAYLIST'
export const SAVE_PLAYLIST_LOCAL = 'SAVE_PLAYLIST_LOCAL'
export const SAVE_PLAYLIST_DB = 'SAVE_PLAYLIST_DB'
